// Code generated by "stringer -type Mode -trimprefix Mode -linecomment"; DO NOT EDIT.

package discovery

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeAny-0]
	_ = x[ModeRO-1]
	_ = x[ModeRW-2]
}

const _Mode_name = "anyrorw"

var _Mode_index = [...]uint8{0, 3, 5, 7}

func (i Mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
