// Code generated by "stringer -type Transport -trimprefix Transport -linecomment"; DO NOT EDIT.

package discovery

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransportPlain-0]
	_ = x[TransportSSL-1]
}

const _Transport_name = "plainssl"

var _Transport_index = [...]uint8{0, 5, 8}

func (i Transport) String() string {
	if i < 0 || i >= Transport(len(_Transport_index)-1) {
		return "Transport(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Transport_name[_Transport_index[i]:_Transport_index[i+1]]
}
