name: checks

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Note: Use exactly match version of tool, to avoid unexpected issues with test on CI.
  GO_VERSION: '1.24.6'

jobs:
  golangci-lint:
    # We want to run on external PRs, but not on our own internal
    # PRs as they'll be run by the push to the branch.
    #
    # The main trick is described here:
    # https://github.com/Dart-Code/Dart-Code/pull/2375
    #
    # Also we want to run it always for manually triggered workflows.
    if: (github.event_name == 'push') ||
      (github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.repository) ||
      (github.event_name == 'workflow_dispatch')

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup requirements
      run: |
        sudo apt-get update -y
        sudo apt install -y --no-install-recommends --no-install-suggests ca-certificates
        sudo update-ca-certificates

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.11.2
        args: >
          --config=.golangci.yml
          --timeout=5m

  codespell:
    if: (github.event_name == 'push') ||
      (github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.repository) ||
      (github.event_name == 'workflow_dispatch')

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup requirements
      run: |
        sudo apt-get update -y
        sudo apt install -y --no-install-recommends --no-install-suggests \
          ca-certificates \
          make \
          python3 \
          python3-pip
        sudo update-ca-certificates

    - name: Install codespell
      run: make deps_codespell

    - name: Run codespell
      run: make codespell

  generate:
    if: (github.event_name == 'push') ||
      (github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.repository) ||
      (github.event_name == 'workflow_dispatch')

    runs-on: ubuntu-24.04

    steps:
    # We need to install git before checkout to have a .git folder:
    # https://github.com/actions/checkout/issues/335
    - name: Setup requirements
      run: |
        sudo apt-get update -y
        sudo apt install -y --no-install-recommends --no-install-suggests \
          bash \
          ca-certificates \
          git \
          make
        sudo update-ca-certificates

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Setup generators
      run: |
        make deps_generate
        echo "~/go/bin" >> $GITHUB_PATH

    - name: Run generate
      run: make generate

    - name: Check if the generated files are different
      run: |
        git diff
        test -z "$(git diff 2>&1)"
